title: Hong's Blog
author: Hongjae.Kim
email: gohn0ae@gmail.com
description: Working NHN
show_excerpts: true
sass:
  sass_dir: _sass
plainwhite:
  name: Hongjae Kim
  tagline: NHN 인프라플랫폼개발팀
  date_format: '%b %-d, %Y'
  
  social_links:
    github: hong-gohn

  sitemap: 'true'
  search: true
  dark_mode: true
  portfolio_image: assets/portfolio.png
  html_lang: en
  condensed_mobile:
    - page
    - post
theme: plainwhite
plugins:
  - jekyll-seo-tag
remote_theme: samarsault/plainwhite-jekyll
disqus_shortname: hong-gohn
url: "https://hong-gohn.github.io"